apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: switch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bitnami/nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-cache
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: switch-app-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Replace with your app's port
  type: ClusterIP

---
#create routes for both clusters
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: switch-app-route
  namespace: switch-app
spec:
  to:
    kind: Service
    name: switch-app-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
                                            # Other option: 'Allow' (serve both HTTP and HTTPS), 'None' (serve only HTTPS)
    # If you have a custom certificate/key you want to use for this route,
    # you can specify them here. Otherwise, OpenShift uses its default ingress certificate.
    # certificate: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN PRIVATE KEY-----
    #   ...
    #   -----END PRIVATE KEY-----
    # caCertificate: |- # Optional: If your service uses a CA certificate that the router should trust for re-encryption
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----

